export const LIGNE_CATEGORIES = ['CAT 1', 'CAT 2', 'CAT 3', 'MINISTERE'];

export const LIGNE_QUALITES = [
  'Direction',
  'Direction Adjointe',
  'Inspection',
  'Direction Régionale',
  'Direction Provinciale',
  'Direction Préfectorale',
  'Sous-Direction des Affaires Sociales et de la Planification',
  "Division de l'Ingénierie Sociale",
  "Service de l'Ingénierie de la Veille Sociale et des Études",
  'Service des Statistiques et des Indicateurs',
  'Division de la Planification Stratégique et de la Programmation',
  "Service de la Planification du Suivi et d'Évaluation des Programmes",
  'Service du Partenariat',
  'Sous-Direction des Affaires Administratives et Financières',
  'Division des Ressources Financières',
  'Service de la Comptabilité',
  'Service du Budget et de la Programmation',
  'Service du Recouvrement',
  "Service de l'Ordonnancement et du Paiement",
  'Division des Ressources Humaines',
  'Service de la Gestion du Personnel',
  'Service de la Couverture Sociale',
  'Service Développement des RH',
  'Division du Patrimoine et de la Logistique',
  'Service du Patrimoine et des Bâtiments',
  'Service des Achats',
  'Service de la Logistique et des Moyens Généraux',
  'Service de la Gestion des Archives',
  "Sous-Direction de l'Assistance Sociale",
  'Division de la Solidarité et de l\'Assistance Sociale',
  "Service de la Solidarité et de l'Action Humanitaire",
  "Service d'Assistance et d'Accompagnement des PSH",
  'Service des Personnes Sans Abri',
  'Division de la Protection et de la Promotion Familiale',
  "Service d'Accompagnement et de Protection de l'Enfance",
  "Service des Établissements d'Accueil et de Protection des Enfants",
  "Service des Structures d'Accueil et d'Aide des PSH",
  'Service de Protection des Personnes Âgées et de la Promotion Familiale',
  "Division de l'Intégration et de l'Autonomisation",
  "Service d'Assistance Sociale à la Femme",
  "Service des Centres d'Accueil et de Protection de la Femme",
  "Service de l'Autonomisation et de l'Insertion Sociale de la Femme",
  "Systèmes d'Information",
  "Division des Systèmes d'Information et de la Transformation Digitale",
  'Service Études et Développement des SI',
  'Service Gestion, Maintenance et Support des SI',
  'Communication et Coopération',
  'Service Presse, Édition et Contribution de Gestion',
  'Service de la Communication',
  'Service de la Coopération',
  'Service du Contentieux et des Affaires Juridiques'
];
